'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReSalesStaff
    
    '''<summary>
    '''outerimgdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents outerimgdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesignation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDeptSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptSection As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJoinDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJoinDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReviewer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrade As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents q4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''placeholderTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeholderTable As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''trYearTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trYearTotal As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdTW_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdTW_Value As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdIndian_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdIndian_Value As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdyearavarage_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdyearavarage_Value As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdPlan_Percentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPlan_Percentage As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdExpect_Percentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdExpect_Percentage As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdExpect_Tires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdExpect_Tires As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdActual_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdActual_Value As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdAchivement_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdAchivement_Value As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdyearTotalExtraTires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdyearTotalExtraTires As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRate As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdPieceRateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPieceRateAmount As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdVariablepay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdVariablepay As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdCoefficient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCoefficient As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFinalAmtVP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFinalAmtVP As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdyearscoreAverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdyearscoreAverage As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''chkPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPass As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkExtend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExtend As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTerm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTerm1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTerm6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTerm6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTermDist1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTermDist1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox9 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox10 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox11 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents remark As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkSame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSame As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkIncrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncrease As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDecrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDecrease As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''finlamnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents finlamnt As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ch1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ch2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblEmpsign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpsign As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblEmpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ch3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Time As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''insert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents print As Global.System.Web.UI.WebControls.LinkButton
End Class
